sys:
  build: librenms
  restart: always
  tty: true
  links:
    - mysql
  volumes:
    - ./librenms/rrd:/opt/librenms/rrd
    - ./librenms/logs/opt/librenms/logs
  environment:
    LIBRENMS_USERNAME: librenms
    LIBRENMS_PASSWORD: librenms
    LIBRENMS_EMAIL: librenms@localhost
    LIBRENMS_THREADS: 4
    LIBRENMS_TZ: America/Los_Angeles
    VIRTUAL_HOST: librenmms.coreos
mysql:
  image: percona:5.6
  volumes:
    - ./mysql/db:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: setmetosomething
    MYSQL_DATABASE: librenms
